export default {

    myDriveColor: "#63bf80",
    myDriveTitle: "MyDrive",
    myDriveDesc: "MyDrive is a Node.js, React, and Mongo.db Google Drive Clone.",
    myDriveGit: "https://github.com/subnub/myDrive",
    myDriveImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/build/images/mydrive.png",
    myDriveLongDesc: "MyDrive is an Open-Source full-stack application I created. MyDrive clearly demonstrates my ability to break applications into small coherent pieces. MyDrive is relatively popular on Github, receiving over 900 stars, 100 forks, and 24,000 views. MyDrive is build with Node.js, React, Mongo.db, and also uses tools like Jest. MyDrive also follows a strict design pattern, throught the whole application, making it easy to read, debug, and add onto later.",
    myDriveDemo: "https://mydrive-demo.herokuapp.com/",

    expensifyColor: "#a7132d",
    expensifyTitle: "Expensify",
    expensifyDesc: "Expensify is a React and Redux based Expense tracker.",
    expensifyGit: "https://github.com/subnub/react-course-expensivify",
    expensifyImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/build/images/expense.png",
    expensifyLongDesc: "Expenisify is based on React, and Redux, and is a way to manage all of your expenses. You can edit, create, and remove expenses. Expensify also uses Firebase as a backend.",
    expensifyDemo: "https://react-course-expensivify.herokuapp.com/",

    portfolioColor: "#282658",
    portfolioTitle: "My Web Portfolio",
    portfolioDesc: "My Web Portfolio is based on React, and Redux.",
    portfolioGit: "https://github.com/subnub/subnub.github.io",
    portfolioImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/build/images/portfolio.png",
    portfolioLongDesc: "My Web Portfolio demonstrates my ability to build an elegant looking Web Application, it uses React, and Redux",

    taskColor: "#f16a55",
    taskTitle: "Task Manager",
    taskDesc: "Task Manager is a Node.js, Express and MongoDB, based backend API for creating tasks",
    taskGit: "https://github.com/subnub/task-manager-api",
    taskImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/build/images/task.png",
    taskLongDesc: "Task Manger is baed on Node.js, Express, and MongoDB. It supports API calls for creating, updating, and deleting task, as well as a simple web UI.",

    syncColor: "#fe1f7c",
    syncTitle: "SyncMessage",
    syncDesc: "Syncmessage is an Android, and Electron application, it sends and receives iMessages",
    syncGit: "https://github.com/subnub/syncmessage-macos-final-public",
    syncImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/build/images/sync.png",
    syncLongDesc: "Syncmessage is an Android Application, with the unique ability to send and receive Apple iMessages. It uses Java-Android for the Android App, Electon for the macOS app, and Firebase for the backend.",
    syncDemo: "https://www.syncmessage-android.com/",

    homeworkColor: "#78a7c3",
    homeworkTitle: "Homework Helper",
    homeworkDesc: "Homework Helper is built with vanilla Javascript, find answers for Homework/Quizzes automatically",
    homeworkGit: "https://github.com/subnub/Homework-helper",
    homeworkImage: "https://raw.githubusercontent.com/subnub/subnub.github.io/master/public/images/chrome_image_main.jpg",
    homeworkLongDesc: "Homework Helper is an Open Source Chome Extension, it allows users to right click on highlighted text/questions, and automatically searches for answers using Quizlet. These answers are then stored in a nice scrollable card list UI, where users can copy answers, or even launch the Quizlet page the answer was found from!\n Homework Helper is build with just vanilla Javascript, no modules were used, this project demostates my ability to work with plain Javascript, as well as tools just as HTML Temlplates.",
    homeworkDemo: "https://chrome.google.com/webstore/detail/homework-helper/dgfigglmnhnamfjbccjoiomogdmglnpa",
}